"""Create career chats table

Revision ID: 12125d4455a4
Revises: 6f8e9e8f3989
Create Date: 2026-07-31 07:11:45.466557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12125d4455a4'
down_revision = '6f8e9e8f3989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_chats')
    # ### end Alembic commands ###
