"""Add career insights to resume analysis

Revision ID: 27dda0c83293
Revises: 486758e9e0ef
Create Date: 2026-07-14 18:42:12.548410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27dda0c83293'
down_revision = '486758e9e0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_insights', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_column('career_insights')

    # ### end Alembic commands ###
