"""Create resume analyses table

Revision ID: 486758e9e0ef
Revises: 0c55a4fa3406
Create Date: 2026-07-10 21:40:45.852560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486758e9e0ef'
down_revision = '0c55a4fa3406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_filename', sa.String(length=255), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_analyses')
    # ### end Alembic commands ###
