"""Create interview preparation table

Revision ID: 72164ae3f1cf
Revises: 27dda0c83293
Create Date: 2026-07-14 19:16:30.534486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72164ae3f1cf'
down_revision = '27dda0c83293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_preparations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['job_applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_preparations')
    # ### end Alembic commands ###
