"""Create resume optimizations table

Revision ID: cb08f7121d8e
Revises: 72164ae3f1cf
Create Date: 2026-07-15 17:36:59.780452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb08f7121d8e'
down_revision = '72164ae3f1cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_optimizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_analysis_id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('optimization', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_analysis_id'], ['resume_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_optimizations')
    # ### end Alembic commands ###
